// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCheckout struct {
	Sku string `json:"sku"`
	Qty int    `json:"qty"`
}

type Product struct {
	Sku   string  `json:"sku"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Qty   int     `json:"-"`
}

type ProductQuantity struct {
	Product *Product `json:"product"`
	Qty     int      `json:"qty"`
}

type ProductTotal struct {
	Products []*ProductQuantity `json:"products"`
	Totals   float64            `json:"totals"`
}
